spring:
  application:
    name: boothix-backend
  flyway:
    locations: classpath:/db/migration
    baselineOnMigrate: true
    enabled: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/boothix
    username: postgres
    password: postgres